version: "3.9"

services:
  otc-app:
    build: .
    container_name: otc-app
    restart: unless-stopped
    volumes:
      - ./update:/app/update
      - ./data:/app/data
      - ./sessions:/app/sessions   
    environment:
      API_ID: "${API_ID}"
      API_HASH: "${API_HASH}"
      BOT_TOKEN: "${BOT_TOKEN}"
      TARGET_GROUP: "${TARGET_GROUP}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
